//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyExtensionsTests.jsonResults {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class jsoncollections {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal jsoncollections() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyExtensionsTests.jsonResults.jsoncollections", typeof(jsoncollections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;label&quot;:&quot;Boolean label&quot;,&quot;labelTrue&quot;:&quot;True&quot;,&quot;labelFalse&quot;:&quot;False&quot;,&quot;type&quot;:&quot;boolean&quot;,&quot;title&quot;:null,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;IsLegalPerson&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string BooleanTestExtractedJson {
            get {
                return ResourceManager.GetString("BooleanTestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;asc&quot;,&quot;colCount&quot;:1,&quot;choices&quot;:[{&quot;value&quot;:&quot;CB1Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;CB1Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;CB1Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;CB1Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;CB1Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;otherText&quot;:&quot;Other choice text&quot;,&quot;hasSelectAll&quot;:true,&quot;selectAllText&quot;:&quot;Select All&quot;,&quot;hasNone&quot;:true,&quot;noneText&quot;:&quot;Select none&quot;,&quot;type&quot;:&quot;checkbox&quot;,&quot;title&quot;:&quot;Choice 1 Title (asc) - All - None&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Checkbox1TestExtractedJson {
            get {
                return ResourceManager.GetString("Checkbox1TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;desc&quot;,&quot;colCount&quot;:2,&quot;choices&quot;:[{&quot;value&quot;:&quot;CB2Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;CB2Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;CB2Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;CB2Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;CB2Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;otherText&quot;:&quot;Other choice text&quot;,&quot;hasSelectAll&quot;:true,&quot;selectAllText&quot;:&quot;Select All&quot;,&quot;hasNone&quot;:false,&quot;noneText&quot;:null,&quot;type&quot;:&quot;checkbox&quot;,&quot;title&quot;:&quot;Choice 2 Title (desc) - All&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Checkbox2TestExtractedJson {
            get {
                return ResourceManager.GetString("Checkbox2TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;asc&quot;,&quot;colCount&quot;:1,&quot;choices&quot;:[{&quot;value&quot;:&quot;CB1Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;CB1Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;CB1Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;CB1Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;CB1Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;otherText&quot;:&quot;Other choice text&quot;,&quot;hasSelectAll&quot;:true,&quot;selectAllText&quot;:&quot;Select All&quot;,&quot;hasNone&quot;:true,&quot;noneText&quot;:&quot;Select none&quot;,&quot;type&quot;:&quot;checkbox&quot;,&quot;title&quot;:&quot;Choice 1 Title (asc) - All - None&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Checkbox3TestExtractedJson {
            get {
                return ResourceManager.GetString("Checkbox3TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;placeHolder&quot;:&quot;entra los datos de contacto&quot;,&quot;rows&quot;:7,&quot;type&quot;:&quot;comment&quot;,&quot;title&quot;:&quot;Datos de contacto&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;},{&quot;placeHolder&quot;:&quot;placeholder 2&quot;,&quot;rows&quot;:14,&quot;type&quot;:&quot;comment&quot;,&quot;title&quot;:&quot;Datos de contacto 2&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:false,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string CommentTestExtractedJson {
            get {
                return ResourceManager.GetString("CommentTestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;random&quot;,&quot;colCount&quot;:3,&quot;hasOther&quot;:false,&quot;otherText&quot;:null,&quot;choices&quot;:[{&quot;value&quot;:&quot;RG3Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;RG3Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;RG3Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;RG3Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;RG3Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;type&quot;:&quot;radiogroup&quot;,&quot;title&quot;:&quot;Radiogroup  3 Title (random)&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string Dropdown1TestExtractedJson {
            get {
                return ResourceManager.GetString("Dropdown1TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;desc&quot;,&quot;choices&quot;:[{&quot;value&quot;:&quot;DD2Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;DD2Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;DD2Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;DD2Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;DD2Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;hasOther&quot;:false,&quot;otherText&quot;:null,&quot;optionCaption&quot;:null,&quot;type&quot;:&quot;dropdown&quot;,&quot;title&quot;:&quot;Dropdown  2 Title (desc)&quot;,&quot;description&quot;:&quot;Dropdown 2 description&quot;,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string Dropdown2TestExtractedJson {
            get {
                return ResourceManager.GetString("Dropdown2TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;random&quot;,&quot;choices&quot;:[{&quot;value&quot;:&quot;DD3Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;DD3Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;DD3Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;DD3Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;DD3Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;hasOther&quot;:false,&quot;otherText&quot;:null,&quot;optionCaption&quot;:null,&quot;type&quot;:&quot;dropdown&quot;,&quot;title&quot;:&quot;Dropdown  3 Title (random)&quot;,&quot;description&quot;:&quot;Dropdown 3 description&quot;,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string Dropdown3TestExtractedJson {
            get {
                return ResourceManager.GetString("Dropdown3TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;maxSize&quot;:250,&quot;type&quot;:&quot;file&quot;,&quot;title&quot;:null,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string FileExtractedJson {
            get {
                return ResourceManager.GetString("FileExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;html&quot;:&quot;&lt;h1&gt;H1 content&lt;/h1&gt;&lt;p&gt;Paragraph&lt;/p&gt;&quot;,&quot;type&quot;:&quot;html&quot;,&quot;title&quot;:null,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string HtmlEditorTestExtractedJson {
            get {
                return ResourceManager.GetString("HtmlEditorTestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;asc&quot;,&quot;colCount&quot;:0,&quot;choices&quot;:[{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg&quot;,&quot;value&quot;:&quot;IP1Val1&quot;,&quot;text&quot;:&quot;Lion&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg&quot;,&quot;value&quot;:&quot;IP1Val2&quot;,&quot;text&quot;:&quot;Giraffe&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/panda.jpg&quot;,&quot;value&quot;:&quot;IP1Val3&quot;,&quot;text&quot;:&quot;Panda&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/camel.jpg&quot;,&quot;value&quot;:&quot;IP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImagePicker1TestExtractedJson {
            get {
                return ResourceManager.GetString("ImagePicker1TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;desc&quot;,&quot;colCount&quot;:2,&quot;choices&quot;:[{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg&quot;,&quot;value&quot;:&quot;IP1Val1&quot;,&quot;text&quot;:&quot;Lion&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg&quot;,&quot;value&quot;:&quot;IP1Val2&quot;,&quot;text&quot;:&quot;Giraffe&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/panda.jpg&quot;,&quot;value&quot;:&quot;IP1Val3&quot;,&quot;text&quot;:&quot;Panda&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/camel.jpg&quot;,&quot;value&quot;:&quot;I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImagePicker2TestExtractedJson {
            get {
                return ResourceManager.GetString("ImagePicker2TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;random&quot;,&quot;colCount&quot;:0,&quot;choices&quot;:[{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg&quot;,&quot;value&quot;:&quot;IP1Val1&quot;,&quot;text&quot;:&quot;Lion&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg&quot;,&quot;value&quot;:&quot;IP1Val2&quot;,&quot;text&quot;:&quot;Giraffe&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/panda.jpg&quot;,&quot;value&quot;:&quot;IP1Val3&quot;,&quot;text&quot;:&quot;Panda&quot;},{&quot;imageLink&quot;:&quot;https://surveyjs.io/Content/Images/examples/image-picker/camel.jpg&quot;,&quot;value&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImagePicker3TestExtractedJson {
            get {
                return ResourceManager.GetString("ImagePicker3TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;columns&quot;:[{&quot;value&quot;:&quot;0&quot;,&quot;text&quot;:&quot;Bad&quot;},{&quot;value&quot;:&quot;1&quot;,&quot;text&quot;:&quot;Mid-Bad&quot;},{&quot;value&quot;:&quot;2&quot;,&quot;text&quot;:&quot;Mid&quot;},{&quot;value&quot;:&quot;3&quot;,&quot;text&quot;:&quot;Mid-Good&quot;},{&quot;value&quot;:&quot;4&quot;,&quot;text&quot;:&quot;Good&quot;}],&quot;rows&quot;:[{&quot;value&quot;:&quot;R0&quot;,&quot;text&quot;:&quot;Superman&quot;},{&quot;value&quot;:&quot;R1&quot;,&quot;text&quot;:&quot;Batman&quot;},{&quot;value&quot;:&quot;R2&quot;,&quot;text&quot;:&quot;Spiderman&quot;},{&quot;value&quot;:&quot;R3&quot;,&quot;text&quot;:&quot;Jocker&quot;}],&quot;isAllRowRequired&quot;:true,&quot;type&quot;:&quot;matrix&quot;,&quot;title&quot;:&quot;MSC Title&quot;,&quot;description&quot;:&quot;MSC DEscription&quot;,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;nam....
        /// </summary>
        internal static string MatrixSingleChoiceExtractedJson {
            get {
                return ResourceManager.GetString("MatrixSingleChoiceExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;asc&quot;,&quot;colCount&quot;:1,&quot;hasOther&quot;:true,&quot;otherText&quot;:&quot;Other choice text&quot;,&quot;choices&quot;:[{&quot;value&quot;:&quot;RG1Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;RG1Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;RG1Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;RG1Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;RG1Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;type&quot;:&quot;radiogroup&quot;,&quot;title&quot;:&quot;Radiogroup 1 Title (asc)&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string Radiogroup1TestExtractedJson {
            get {
                return ResourceManager.GetString("Radiogroup1TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:null,&quot;colCount&quot;:2,&quot;hasOther&quot;:false,&quot;otherText&quot;:null,&quot;choices&quot;:[{&quot;value&quot;:&quot;RG2Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;RG2Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;RG2Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;RG2Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;RG2Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;type&quot;:&quot;radiogroup&quot;,&quot;title&quot;:&quot;Radiogroup  2 Title (desc)&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string Radiogroup2TestExtractedJson {
            get {
                return ResourceManager.GetString("Radiogroup2TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;choicesOrder&quot;:&quot;random&quot;,&quot;colCount&quot;:3,&quot;hasOther&quot;:false,&quot;otherText&quot;:null,&quot;choices&quot;:[{&quot;value&quot;:&quot;RG3Val1&quot;,&quot;text&quot;:&quot;Choice 1&quot;},{&quot;value&quot;:&quot;RG3Val2&quot;,&quot;text&quot;:&quot;Choice 2&quot;},{&quot;value&quot;:&quot;RG3Val3&quot;,&quot;text&quot;:&quot;Choice 3&quot;},{&quot;value&quot;:&quot;RG3Val4&quot;,&quot;text&quot;:&quot;Choice 4&quot;},{&quot;value&quot;:&quot;RG3Val5&quot;,&quot;text&quot;:&quot;Choice 5&quot;}],&quot;type&quot;:&quot;radiogroup&quot;,&quot;title&quot;:&quot;Radiogroup  3 Title (random)&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;ContactData&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string Radiogroup3TestExtractedJson {
            get {
                return ResourceManager.GetString("Radiogroup3TestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;rateMin&quot;:1,&quot;rateMax&quot;:10,&quot;rateStep&quot;:1,&quot;rateValues&quot;:[],&quot;minRateDescription&quot;:null,&quot;maxRateDescription&quot;:null,&quot;type&quot;:&quot;rating&quot;,&quot;title&quot;:&quot;Rating with values&quot;,&quot;description&quot;:&quot;&quot;,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;IsLegalPerson&quot;},{&quot;rateMin&quot;:1,&quot;rateMax&quot;:5,&quot;rateStep&quot;:1,&quot;rateValues&quot;:[{&quot;value&quot;:&quot;RTVal1&quot;,&quot;text&quot;:&quot;Val 1&quot;},{&quot;value&quot;:&quot;RTVal2&quot;,&quot;text&quot;:&quot;Val 2&quot;},{&quot;value&quot;:&quot;RTVal3&quot;,&quot;text&quot;:&quot;Val 3&quot;},{&quot;value&quot;:&quot;RTVal4&quot;,&quot;text&quot;:&quot;Val 4&quot;},{&quot;value&quot;:&quot;RTVal5&quot;,&quot;text&quot;:&quot;Val 5&quot;},{&quot;value&quot;:&quot;RTVal6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RatingTestExtractedJson {
            get {
                return ResourceManager.GetString("RatingTestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;elements&quot;:[{&quot;placeHolder&quot;:&quot;Document Id Card&quot;,&quot;inputType&quot;:&quot;text&quot;,&quot;type&quot;:&quot;text&quot;,&quot;title&quot;:&quot;Put Here your DNI&quot;,&quot;description&quot;:null,&quot;visible&quot;:true,&quot;isRequired&quot;:false,&quot;startWithNewLine&quot;:true,&quot;name&quot;:&quot;DocumentId&quot;}],&quot;name&quot;:&quot;Page1&quot;}]}.
        /// </summary>
        internal static string SingleInputTestExtractedJson {
            get {
                return ResourceManager.GetString("SingleInputTestExtractedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pages&quot;:[{&quot;name&quot;:&quot;Page1&quot;,&quot;elements&quot;:[{&quot;placeHolder&quot;:&quot;Put Here your DNI&quot;,&quot;inputType&quot;:&quot;text&quot;,&quot;type&quot;:&quot;text&quot;,&quot;title&quot;:&quot;Document Id Card&quot;,&quot;isRequired&quot;:false,&quot;name&quot;:&quot;DocumentId&quot;}]}]}.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
    }
}
